export const services = [
  {
    name: 'Anaesthesiology',
    slug: 'anaesthesiology',
    description: 'Comprehensive anesthesia services for safe and pain-free surgical procedures. Our experts ensure patient comfort and safety before, during, and after surgery.',
    departmentHead: 'Dr. Asha Reddy',
    facilities: ['Pre-operative evaluation', 'General anesthesia', 'Sedation techniques', 'Post-operative pain management'],
  },
  {
    name: 'Cardiac Surgery',
    slug: 'cardiac-surgery',
    description: 'Advanced surgical treatment for heart-related conditions including bypass surgery, valve replacement, and minimally invasive heart procedures.',
    departmentHead: 'Dr. Vikram Narayan',
    facilities: ['Open-heart surgery', 'Valve replacement', 'Minimally invasive techniques', 'Post-surgery ICU care'],
  },
  {
    name: 'Dentistry',
    slug: 'dentistry',
    description: 'Comprehensive dental care including preventive, restorative, and cosmetic treatments for patients of all ages.',
    departmentHead: 'Dr. Sneha Kapoor',
    facilities: ['Tooth extraction', 'Root canal treatment', 'Cosmetic dentistry', 'Orthodontics'],
  },
  {
    name: 'Cardiology',
    slug: 'cardiology',
    description: 'Diagnosis and management of heart conditions including ECG, echocardiograms, angiography, and interventional cardiology.',
    departmentHead: 'Dr. Rajeev Menon',
    facilities: ['ECG & ECHO', 'Stress tests', 'Angiography', 'Heart failure management'],
  },
  {
    name: 'ENT',
    slug: 'ent',
    description: 'Specialized care for ear, nose, and throat disorders, including hearing tests, sinus treatments, and ENT surgeries.',
    departmentHead: 'Dr. Meenakshi Rao',
    facilities: ['Hearing assessments', 'Endoscopic sinus surgery', 'Microscopic ear surgery', 'Tonsillectomy'],
  },
  {
    name: 'Neurology',
    slug: 'neurology',
    description: 'Expert diagnosis and treatment for neurological conditions such as stroke, epilepsy, Parkinson’s disease, and migraines.',
    departmentHead: 'Dr. Sandeep Deshmukh',
    facilities: ['EEG & EMG', 'Stroke care', 'Epilepsy management', 'Neuro-rehabilitation'],
  },
  {
    name: 'Ophthalmology',
    slug: 'ophthalmology',
    description: 'Comprehensive eye care including vision testing, cataract surgery, and treatment for glaucoma and retinal diseases.',
    departmentHead: 'Dr. Priya Natarajan',
    facilities: ['Vision testing', 'Cataract & LASIK surgery', 'Glaucoma care', 'Retina treatment'],
  },
  {
    name: 'Gastroenterology – Surgical',
    slug: 'gastroenterology-surgical',
    description: 'Surgical treatment for gastrointestinal disorders including hernia, gallbladder removal, and colorectal surgeries.',
    departmentHead: 'Dr. Arvind Krishna',
    facilities: ['Laparoscopic surgery', 'Hernia repair', 'Colorectal surgery', 'Gallbladder removal'],
  },
];
